version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: attendance_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: attendance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: attendance_redis

  springboot:
    build: ./backend-spring
    container_name: attendance_springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendance_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - postgres
    expose:
      - "8080"

  fastapi:
    build: ./ml-fastapi
    container_name: attendance_fastapi
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/attendance_db
      REDIS_URL: redis://attendance_redis:6379/0
    depends_on:
      - postgres
      - redis
    expose: # expose instead of ports because Nginx will forward traffic
      - "8000"

  frontend:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile # or Dockerfile.dev if coding
    container_name: attendance_frontend
    environment:
      NEXT_PUBLIC_API_URL: /api
      NEXT_PUBLIC_ML_API_URL: /ml
    depends_on:
      - springboot
      - fastapi
    expose:
      - "3000"

  frontend-dev:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile.dev
    container_name: attendance_frontend_dev
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost/api
      NEXT_PUBLIC_ML_API_URL: http://localhost/ml
    volumes:
      - ./frontend-nextjs:/app
      - /app/node_modules
    depends_on:
      - springboot
      - fastapi

  nginx:
    image: nginx:1.27
    container_name: attendance_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - springboot
      - fastapi

volumes:
  postgres_data:
