version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: attendance_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: attendance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot:
    build: ./backend-spring
    container_name: attendance_springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendance_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - postgres
    expose:
      - "8080"

  frontend-dev:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile.dev
    container_name: attendance_frontend_dev
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost/api
      NEXT_PUBLIC_ML_API_URL: http://localhost/ml
    volumes:
      - ./frontend-nextjs:/app
      - /app/node_modules
    depends_on:
      - springboot

  nginx:
    image: nginx:1.27
    container_name: attendance_nginx
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-dev
      - springboot

volumes:
  postgres_data:
