version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # face-api:
  #   build: .
  #   container_name: face-api
  #   restart: unless_stopped
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_DB=0
